

[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --tb=short
    
# marker 구분
markers = 
    # 플랫폼
    aos: Android 테스트
    ios: iOS 테스트

    # 환경
    real: 실기기
    emulator: Android 에뮬레이터
    simulator: iOS 시뮬레이터

    # 브라우저
    chrome: Chrome 브라우저
    samsung: Samsung Browser
    safari: Safari 브라우저

    # 실행순서
    order: 테스트 실행 순서 지정

